syncs:
  - repos:
      - rahulmodiphilips/repoa
      - rahulmodiphilips/repob
    files:
      - src: filefour.js
        dest: project_A

rahulmodiphilips/repoa:
  - filefour.js

rahulmodiphilips/repob:
  - project_A/