source:
  copy_from:
    - "project_A/pub"
target:
  repo: "rahulmodiphilips/repob"
  maxsize_commit_MB: 1000
  commit_message: "just publishing"
  copy_to:
    - "project_A"
  remove_after_copy:
    - "project_B/secret_gadgets"
